version: '3.8'

services:
  proxy:
    build:
      context: .
    container_name: medicalclinic-proxy
    ports:
      - '8081:8080'
    networks:
      - medclinic-network

networks:
  medclinic-network:
    name: medclinic-network
    external: true
