spring.application.name=githubproxy
#Feign
spring.cloud.openfeign.client.config.githubproxy.url=https://api.github.com
logging.level.com.wardzionn.githubproxy.client.PatientClient=DEBUG
#circuitbreaker
spring.cloud.openfeign.circuitbreaker.enabled=true
