spring.application.name=githubproxy
#Feign
spring.cloud.openfeign.client.config.visitClient.url=http://app:8080
spring.cloud.openfeign.client.config.doctorClient.url=http://app:8080
spring.cloud.openfeign.okhttp.enabled=true
logging.level.com.wardzionn.githubproxy.client.VisitClient=DEBUG
logging.level.com.wardzionn.githubproxy.client.DoctorClient=DEBUG
#circuitbreaker
spring.cloud.openfeign.circuitbreaker.enabled=true

#port
server.port=8080
